name: call-center-rag
services:
  rag_api:
    build: .
    image: call_center_rag_api:latest
    environment:
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_USER=admin
      - OPENSEARCH_PASSWORD=admin
      - YANDEX_API_KEY=${YANDEX_API_KEY}
  opensearch:
    image: opensearchproject/opensearch:3
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin
    ports:
      - "9200:9200"
      - "9600:9600"
